[package]
name = "flotsync_discovery_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
flotsync_discovery = { path = "../flotsync_discovery" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
simple_logger = "5"
