[flotsync.examples.replicated-checklist]
local-member = "raspberrypi"
store-path = "stores/raspberrypi.sqlite"
group-id = 17872
ordered-members = ["current-system", "raspberrypi"]

[flotsync.replication.runtime]
local-endpoint-bind-addr = "0.0.0.0:45101"

[[flotsync.replication.runtime.static-peer-routes]]
name = "current-system"
protocol = "udp"
ip = "192.168.178.74"
port = 45100
