[package]
name = "flotsync_utils"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
async-std = { workspace = true }
futures-util = { workspace = true }
hashbrown = { workspace = true }
iddqd = { workspace = true }
kompact = { workspace = true }
snafu = { workspace = true }

[dev-dependencies]
proptest = "1"
